// Event constants
export const SOCKET_EVENTS = {
	USER_CONNECTED: "user has connected",
	USER_DISCONNECTED: "user has disconnected",
	USERNAME_ASSIGNED: "username assigned",
	SEND_MESSAGE: "send message",
	RECEIVE_MESSAGE: "receive message",
	CHANGE_ROOM_STATUS: "change room status",
	AFTER_CHANGE_ROOM_STATUS: "after change room status",
	SEND_POSITION: "send position",
	RECEIVE_POSITION: "receive position",
	SEND_MONEY: "send money",
	SEND_TURN: "send turn",
	RECEIVE_TURN: "receive turn",
	SEND_VOTE: "send vote",
	RECEIVE_VOTE: "receive vote",
	RECEIVE_MONEY: "receive money",
	SEND_TRADE_OFFER: "send trade offer",
	RECEIVE_TRADE_OFFER: "receive trade offer",
	CONFIRM_TRADE_OFFER: "confirm trade offer",
	RECEIVE_CONFIRM_TRADE_OFFER: "receive confirm trade offer",
	BUY_PROPERTY: "buy property",
	PROPERTY_BOUGHT: "property bought",
	SEND_DICE_ROLL: "send dice roll",
	GET_DICE_ROLL: "get dice roll",
	CREATE_ROOM: "create room",
	GET_ALL_ROOMS: "get all rooms",
	JOIN_ROOM: "join room",
	JOIN_RANDOM_ROOM: "join random room",
	PLAYER_JOINED: "player joined",
	PLAYER_LEFT: "player left",
	GAME_LOOP: "game loop",
	REMOVE_PLAYER: "remove player",
	LEAVE_ROOM: "leave room",
	LEAVE_GAME: "leave game",
	CHAT_HISTORY: "chat history",
	ERROR: "error",
	YOUR_VOTES: "your votes",
} as const;
